version: 2.1 #

jobs: # jobs related configuration will present in jobs keyword
    build: # name of the job
        docker: # docker related configuration will present in docker keyword
            # this will be the primary image in this case
            - image: circleci/python:3.6.2-stretch-browsers  # circleci convience image
              # this image has the support python with web browser
              environment: # environment related configuration will present in environment keyword
                TEST_DATABASE_URL : postgresql://root@localhost/circle_test?sslmode=disable
                # Database URL for testing purposes with SSL disabled
            - image: circleci/postgres:9.6.2-alpine # circleci convience image for postgres database
        steps: # steps related configuration will present in steps keyword
            - checkout # checkout the code from the repository
            - run: # run the command in the shell
                name: installing pql client for the communication
                command: sudo apt-get install postgresql-client-9.6 # install the postgresql client
            - run: # checking the user as which is the user
                command: whoami # print the user name
            - run:
                name: creating the table named as test
                command: | # testing the connnection as below
                    psql -d $TEST_DATABASE_URL -c "CREATE TABLE test (name char(25));"
            - run:
                name: Inserting element to the Table
                command: | # testing the connnection as below
                    psql -d $TEST_DATABASE_URL -c "INSERT INTO test (name) VALUES ('circleci');"

            - run:
                name: selecting all entry from test DB
                command: | # testing the connnection as below
                   psql -d $TEST_DATABASE_URL -c "SELECT * FROM test;"

workflows: # workflows related configuration will present in workflows keyword
   build_workflow:
        jobs: # jobs related configuration will present in jobs keyword
            - build # name of the job
