version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - run:
          name: Update package list
          command: sudo apt-get update
      - run:
          name: Install PostgreSQL client
          command: sudo apt-get install -y postgresql-client
      - run:
          command: whoami
      - run:
          name: Creating the table named as test
          command: |
            psql -d $TEST_DATABASE_URL -c "CREATE TABLE test (name char(25));"
      - run:
          name: Inserting element to the Table
          command: |
            psql -d $TEST_DATABASE_URL -c "INSERT INTO test (name) VALUES ('circleci');"
      - run:
          name: Selecting all entry from test DB
          command: |
            psql -d $TEST_DATABASE_URL -c "SELECT * FROM test;"

workflows:
  build_workflow:
    jobs:
      - build
